### ISSUE TITLE
Overcoming limitation of react-dnd:  Cannot have two HTML5 backends at the same time.

### ISSUE THREAD

**Issue by mauron85** [palantir/react-mosaic#17]
Firstly I must say thank you palantir for this great project.

As far I understand react-mosaic is using react-dnd for all drag and drop stuff. My problem is, that I would like to put another component which is also using react-dnd with custom drag layer. And this seems be problem as react-dnd doesn't seems to support two HTML5 backends.

How to reproduce:
I've made sample app (which is react-mosaic and react-dnd custom drag layer example put into one of the MosaicWindow).

https://jsfiddle.net/mauron85/4kpLqac0/

As you can see dragging works in component, but dragging and resizing of MosaicWindows doesn't work. If you open browser console, I can see error:
```
Uncaught Error: Cannot have two HTML5 backends at the same time.
```
Any ideas how this can be solved?

**Comment by nomcopter** [comment]
Yeah this react-dnd issue is pretty bothersome. It would be great if it could just delegate https://github.com/react-dnd/react-dnd/issues/708.
In the meantime, for your particular example, if you remove the `DragDropContext` from `DragAroundCustomLayer` (as done [here](https://jsfiddle.net/4kpLqac0/18/)) it all works as expected because they happen to be nested. Does this solve your use case?
I'll make a release that exports `Mosaic` without the `DragDropContext` so that if you want siblings with drag and drop then you can just decorate a higher-level component as a workaround.

**Comment by mauron85** [comment]
@nomcopter. thank you, removing context works in this simple example. But actually realized that my real app is more complex so Mosaic without the DragDropContext is more than welcome.

**Comment by mauron85** [comment]
Closing as `MosaicWithoutDragDropContext` solved this. Many thanks.
