### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by JunyuanZheng** [palantir/react-mosaic#54]
#### Actual behavior
I used to use react-split-panel, and there is no huge performance issue. After switching to react-mosaic, I notice a huge drop in performance.

Based on the data I got from Chrome Performance Measure Tool. The JSHeap increased from 50MB to 70MB, Notes increased from 1000 to 5000, Listeners increased from 300 to 500.

Can someone give me some suggestion how to find the issue?

**Comment by bradennapier** [comment]
@JunyuanZheng did you modify the css?  I ran into that, my issue is somewhere here you can find.  It was largely due to overlapping layers or something, not really sure what it was honestly.  I ended up resolving it for the most part.

Also - the issues I ran into were almost completely due to "development" - once trying it with env set to "production" all was flawless.

**Comment by nomcopter** [comment]
Can you link an example repo? Happy to look into it.

And no the CSS file is included in the npm artifact. It should be in the root of it `react-mosaic-component.css`

**Comment by JunyuanZheng** [comment]
sorry, i will try to reproduce this issue in a new repo, and let's see.

**Comment by nomcopter** [comment]
Closing without a repro.
